name: test
on: [push, pull_request]

jobs:
  host:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy,rustfmt
      - run: cargo fmt --all --check
      - run: cargo clippy --all --all-targets
      - run: cargo test

  cross:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - i686-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cross --git https://github.com/cross-rs/cross
      - run: cross test --target ${{ matrix.target }}
